apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zerossl-issuer.fullname" . }}-controller
  namespace: {{ include "zerossl-issuer.namespace" . }}
  labels:
    {{- include "zerossl-issuer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zerossl-issuer.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "zerossl-issuer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                {{- with .Values.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          {{- if .Values.leaderElection.enabled }}
          - --leader-elect
          {{- end }}
          - --health-probe-bind-address=:8081
          {{- if .Values.metrics.enabled }}
          - --metrics-bind-address=:{{ .Values.metrics.port }}
          - --metrics-secure={{ .Values.metrics.secure }}
          {{- end }}
          - --max-concurrent-reconciles={{ .Values.controller.maxConcurrentReconciles }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      serviceAccountName: {{ include "zerossl-issuer.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10 