# This rule is not used by the project zerossl-issuer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to read cluster issuers and their status.
# This role is intended for users who need read-only access.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zerossl-issuer
    app.kubernetes.io/managed-by: kustomize
  name: clusterissuer-viewer-role
rules:
- apiGroups:
  - zerossl.cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zerossl.cert-manager.io
  resources:
  - clusterissuers/status
  verbs:
  - get 