# This rule is not used by the project zerossl-issuer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over zerossl.zerossl.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zerossl-issuer
    app.kubernetes.io/managed-by: kustomize
  name: issuer-admin-role
rules:
- apiGroups:
  - zerossl.zerossl.dev
  resources:
  - issuers
  verbs:
  - '*'
- apiGroups:
  - zerossl.zerossl.dev
  resources:
  - issuers/status
  verbs:
  - get
