# This rule is not used by the project zerossl-issuer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the zerossl.zerossl.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zerossl-issuer
    app.kubernetes.io/managed-by: kustomize
  name: issuer-editor-role
rules:
- apiGroups:
  - zerossl.zerossl.dev
  resources:
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zerossl.zerossl.dev
  resources:
  - issuers/status
  verbs:
  - get
