# This rule is not used by the project zerossl-issuer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to zerossl.zerossl.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zerossl-issuer
    app.kubernetes.io/managed-by: kustomize
  name: issuer-viewer-role
rules:
- apiGroups:
  - zerossl.zerossl.dev
  resources:
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zerossl.zerossl.dev
  resources:
  - issuers/status
  verbs:
  - get
