---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zerossl.cert-manager.io
  resources:
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zerossl.cert-manager.io
  resources:
  - issuers/finalizers
  verbs:
  - update
- apiGroups:
  - zerossl.cert-manager.io
  resources:
  - issuers/status
  verbs:
  - get
  - patch
  - update
