apiVersion: zerossl.zerossl.dev/v1alpha1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: zerossl-issuer
    app.kubernetes.io/managed-by: kustomize
  name: issuer-sample
spec:
  # TODO(user): Add fields here
