apiVersion: zerossl.cert-manager.io/v1alpha1
kind: Issuer
metadata:
  name: issuer-sample
spec:
  # Reference to a secret containing the ZeroSSL API key
  apiKeySecretRef:
    name: zerossl-api-key
    key: api-key
  # Optional: Number of days the certificate should be valid for (default: 90)
  validityDays: 90
  # Optional: Enable strict domain validation (default: true)
  strictDomains: true
---
# Example secret containing the ZeroSSL API key
apiVersion: v1
kind: Secret
metadata:
  name: zerossl-api-key
type: Opaque
stringData:
  api-key: "your-api-key-here"
