apiVersion: zerossl.cert-manager.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: zerossl-dns
spec:
  # Reference to a secret containing the ZeroSSL API key
  apiKeySecretRef:
    name: zerossl-api-key
    key: api-key
  # Optional: Number of days the certificate should be valid for (default: 90)
  validityDays: 90
  # Optional: Enable strict domain validation (default: true)
  strictDomains: true
  # DNS solvers configuration for various domains
  solvers:
  - dns01:
      route53:
        accessKeyID: AKIAEXAMPLE123456789
        hostedZoneID: Z2E9THH2A4HU6P
        region: us-east-1
        secretAccessKeySecretRef:
          key: secret
          name: route53-credentials
    selector:
      dnsZones:
      - example.com
  - dns01:
      route53:
        accessKeyID: AKIAEXAMPLE987654321
        hostedZoneID: Z07844392UF3VO9M8SHRR
        region: us-east-1
        secretAccessKeySecretRef:
          key: secret
          name: route53-credentials
    selector:
      dnsZones:
      - example.org
---
# Example secret containing the ZeroSSL API key
apiVersion: v1
kind: Secret
metadata:
  name: zerossl-api-key
  namespace: cert-manager
type: Opaque
stringData:
  api-key: "your-api-key-here"
---
# Example secret containing the Route53 secret access key
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials
  namespace: cert-manager
type: Opaque
stringData:
  secret: "your-route53-secret-access-key-here" 